title: Mariya Brovkina # your name (or website title) here
 
<img align= "left" src="/images/mylogo.jpeg" alt="mypic"/>
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Portfolio Page
  <br><br>
  Email: kandushk@gmail.com 
  <a href="https://www.linkedin.com/in/maria-brovkina-45139b15b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
